"""Viewport picking for transient Blender geometry selections."""

from __future__ import annotations

import json

import bpy
from bpy_extras import view3d_utils

from ...core.references import TopoReference
from ..adapter import load_document_from_scene, rebuild_part
from ..viewport.sketch_overlay import (
    clear_face_selection,
    set_face_hover,
    set_face_selection,
    tag_redraw,
)
from ..viewport.provenance import get_face_provenance


def _window_region(context):
    return next(
        (region for region in context.area.regions if region.type == "WINDOW"),
        None,
    )


def _raycast(context, event):
    region = _window_region(context)
    if region is None:
        return None
    region_3d = context.space_data.region_3d
    coordinate = (event.mouse_x - region.x, event.mouse_y - region.y)
    origin = view3d_utils.region_2d_to_origin_3d(region, region_3d, coordinate)
    direction = view3d_utils.region_2d_to_vector_3d(region, region_3d, coordinate)
    hit, _location, _normal, polygon_index, obj, _matrix = context.scene.ray_cast(
        context.evaluated_depsgraph_get(), origin, direction
    )
    if not hit or obj is None:
        return None
    active_part = load_document_from_scene(context.scene).active_part
    if active_part is None or obj.get("cad_part_id") != active_part.id:
        return obj, polygon_index, None
    reference = _face_reference(obj, polygon_index)
    return obj, polygon_index, reference


def _face_reference(obj, polygon_index: int) -> TopoReference | None:
    if not obj.get("cad_generated"):
        return None
    return get_face_provenance(obj).get(polygon_index)


class PARAMETRIC_CAD_OT_select_face(bpy.types.Operator):
    bl_idname = "parametric_cad.select_face"
    bl_label = "Select Face"
    bl_description = "Select a planar face generated by a simple Extrude"
    bl_options = {"BLOCKING"}

    def invoke(self, context, _event):
        if context.area.type != "VIEW_3D":
            return {"CANCELLED"}
        part = load_document_from_scene(context.scene).active_part
        if part is None:
            self.report({"ERROR"}, "Create a Part Studio first")
            return {"CANCELLED"}
        # Rebuild on entry also rehydrates the runtime-only provenance registry
        # after a .blend file has been reopened.
        rebuild_part(context.scene, part.id)
        clear_face_selection()
        context.window_manager.modal_handler_add(self)
        context.area.header_text_set("CAD: click a supported planar face; Esc cancels")
        return {"RUNNING_MODAL"}

    def modal(self, context, event):
        if event.type in {"ESC", "RIGHTMOUSE"}:
            set_face_hover(None)
            context.area.header_text_set(None)
            return {"CANCELLED"}
        if event.type == "MOUSEMOVE":
            set_face_hover(_raycast(context, event))
            return {"RUNNING_MODAL"}
        if event.type != "LEFTMOUSE" or event.value != "PRESS":
            return {"RUNNING_MODAL"}

        hit = _raycast(context, event)
        reference = hit[2] if hit is not None else None
        if reference is None:
            self.report(
                {"WARNING"},
                "This face cannot yet be used as a persistent CAD reference.",
            )
            set_face_hover(None)
            context.area.header_text_set(None)
            return {"FINISHED"}

        ui = context.scene.parametric_cad_ui
        ui.selected_face_reference = json.dumps(
            reference.to_dict(), separators=(",", ":"), sort_keys=True
        )
        set_face_selection(hit)
        set_face_hover(None)
        context.area.header_text_set(None)
        self.report({"INFO"}, f"Selected {reference.role.replace('_', ' ').title()}")
        tag_redraw()
        return {"FINISHED"}


CLASSES = (PARAMETRIC_CAD_OT_select_face,)
